import { Site } from './types';

export const SITES: Site[] = [
    { name: "厂长资源", main_url: "https://www.czzymovie.com/", backup_url: "https://www.czzy.site/", tags: ["在线", "BT"] },
    { name: "NO视频", main_url: "https://www.novipnoad.cc/", backup_url: "https://findno.tv/", tags: ["在线"] },
    { name: "PPnix", main_url: "https://www.ppnix.com/cn/", backup_url: "", tags: ["在线"] },
    { name: "在线之家", main_url: "https://www.zxzjhd.com/", backup_url: "https://www.zxzjys.com", tags: ["在线"] },
    { name: "修罗影视", main_url: "https://xl01.com.de/", backup_url: "https://xlys.me/", tags: ["在线", "BT"] },
    { name: "七味", main_url: "https://www.qmp4.com", backup_url: "https://www.qn63.com/", tags: ["网盘", "BT"] },
    { name: "GoPlay", main_url: "https://goplay.su/", backup_url: "https://discord.com/invite/yY2P3DQR8S", tags: ["在线"] },
    { name: "Alist网盘", main_url: "https://pan.mediy.cn", backup_url: "https://al.chirmyram.com", tags: ["在线"] },
    { name: "两个BT", main_url: "https://www.bttwo.me", backup_url: "https://bttwo.vip/", tags: ["在线", ""] },
    { name: "玩偶哥哥", main_url: "https://www.wogg.one", backup_url: "", tags: ["网盘"] },
    { name: "老K", main_url: "https://docs.qq.com/doc/DTk5EaVdWY2R6ZnBk", backup_url: "", tags: ["网盘"] },
    { name: "4k指南[原盘]", main_url: "https://4kzn.com", backup_url: "", tags: ["网盘"] },
    { name: "混合盘", main_url: "https://hunhepan.com/search", backup_url: "https://hhp.panso.me", tags: ["网盘"] },
    { name: "PanSearch", main_url: "https://pansearch.me/", backup_url: "", tags: ["网盘"] },
    { name: "爱盼", main_url: "https://www.aipan.me", backup_url: "", tags: ["网盘"] },
    { name: "阿里云资源", main_url: "https://slowread.net/", backup_url: "", tags: ["网盘"] },
    { name: "ShowBox", main_url: "https://www.showbox.media/", backup_url: "", tags: ["网盘"] },
    { name: "AGE动漫", main_url:"https://www.agedm.io/", backup_url:"https://www.age.tv/", tags:["在线"]},
    { name: "EE3", main_url: "https://ee3.me/", backup_url: "https://rips.cc/", tags: ["在线"] },
    { name: "Flixer", main_url:"https://flixer.su/", backup_url:"https://discord.com/invite/Z9Hjeqe4Fr", tags:["在线"]},
    { name: "Cineby", main_url:"https://www.cineby.gd/", backup_url:"https://www.fmovies.gd/", tags:["在线"]},
    { name: "BrocoFlix", main_url:"https://brocoflix.xyz/", backup_url:"https://rentry.co/KipsSites", tags:["在线"]},
    { name: "Mapple", main_url:"https://mapple.mov/", backup_url:"https://mapple.site/", tags:["在线"]},
    { name: "P-Stream", main_url:"https://pstream.mov", backup_url:"https://discord.com/invite/jZ6kkzADWS", tags:["在线"]},
    { name: "BT之家", main_url: "https://1lou.one/", backup_url: "https://1lou.cc/", tags: ["BT", "网盘"] },
    { name: "磁力熊", main_url: "https://www.cilixiong.org", backup_url: "https://www.cilixiong.cc", tags: ["BT"] },
    { name: "磁力帝", main_url: "https://cldcld.cc", backup_url: "https://cldcld.top", tags: ["BT"] },
    { name: "1337X", main_url: "https://1337x.to/", backup_url: "https://1337x-status.org/", tags: ["BT"] },
    { name: "YTS", main_url: "https://yts.mx/", backup_url: "https://gosites.org/yts", tags: ["BT"] },
    { name: "EXT", main_url: "https://ext.to/", backup_url: "", tags: ["BT"] },
    { name: "BDigg", main_url: "https://btdig.com/", backup_url: "", tags: ["BT"] },
    { name: "Knaben", main_url: "https://knaben.org/", backup_url: "http://knabenxyzjl3bt5al7awroewfkg37x6duutapjytdib4w42mk2kiqpid.onion/", tags: ["BT"] },
    { name: "iDope", main_url: "https://idope.hair", backup_url: "", tags: ["BT"] },
    { name: "ACG.RIP", main_url: "https://acg.rip", backup_url: "", tags: ["BT"] },
    { name: "LimeTorrents", main_url: "https://www.limetorrents.asia", backup_url: "https://limetorrent.si/", tags: ["BT"] },
    { name: "ExtraTorrent", main_url: "https://extratorrent.st", backup_url: "", tags: ["BT"] },
];
